spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: password
    username: root

#__________pour les mails _______________________________________
  mail:
    host: smtp.mailjet.com
    port: 587
    username: 01bc950fcb3cf0c8a764f3ca631b35c2
    password: 4451b586d8c764578fe3f63cc78133f5
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#_________________________________________________________________

vitalitte-project:
  app:
    controller:
      max-age: 3600
    scheduled:
      fixed-delay:
        delete-unpaid-registrations: 14400000 # provoque l'effacement des inscriptions non finalisées toutes les 4h
    jwtExpirationMs: 36000000 # 8h de connexion
